### PR TITLE
Diracsum fixes

### PR DESCRIPTION
**Pull request by TheBB**
Most importantly, they're now normalized with integral 1.

### CODE REVIEW

**Comment by TheBB** [comment]
jenkins build this please

**Comment by akva2** [comment]
I don't quite get what the normalization is about, please ellaborate.

**Comment by akva2** [comment]
jenkins build this please

**Comment by TheBB** [comment]
A Dirac function should have integral 1. There's two issues on current master: the integral of the generated functions aren't 1, and they also aren't independent of eps. The 1/eps^d factor takes care of the latter (I'm not sure what the eps^2 factor was doing there). For the former, I calculated the integral of exp(-1/(1-r^2)) on the unit balls to get the right factors.

**Comment by akva2** [comment]
k makes sense, i was confused thinking it was a real dirac and wondered quadrature wtf, but i know remember it is regularized so then it ticked.  i just coded what was written down in some document i was handed (incl the eps^2) factor so i guess i inherited somebody's mistake.

**Pull request merged**
